soporte a browsers sin workers mejoras en codigo del worker adicion_model
se meoro la interfaz de listado de productos

se mejoro el polugin de inventario

se mejoro  la UI del plugin alekeyboard

diff --git a/app/vendors/spooler/spooler_srv b/app/vendors/spooler/spooler_srv
--- a/app/vendors/spooler/spooler_srv
+++ b/app/vendors/spooler/spooler_srv
@@ -1,57 +1,176 @@
-#set -x
-#!/bin/bash
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          skeleton
+# Required-Start:    $all
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Spooler de impresion fiscal
+# Description:       Este archivo inicia el servicio de impresión fiscal de Hasar
+### END INIT INFO
 
-SCRIPT=hasar_spooler.sh
-DIA=`date +%d-%m-%y`
-SCRIPTKEEPALIVE=/var/www/ristorantino/app/vendors/spooler/hasar_spooler_keep_alive.sh
+# Author: Ale Vilar <alevilar@gmail.com>
+
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Este archivo inicia el servicio de impresión fiscal de Hasar"
+NAME=hasar_spooler.sh
+DAEMON=/var/www/works/ristorantino/app/vendors/spooler/$NAME
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+DAEMON_ARGS=""
+
 
 CARPETA_FUENTE=/tmp/fuente
 CARPETA_DESTINO=/tmp/dest
+LOG_FILE=/tmp/spooler.log
+CARPETA_TEMP=/tmp
+
+# Ejemplo de ejecucion del spooler
+# spooler -p ttyUSB0 -s /tmp/fuente -a /tmp/destino -l -d /tmp/log.log -b /tmp
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+echo "pasopo"
+# Creo la carpeta destino si no existe
+if [ ! -d "$CARPETA_DESTINO" ]; then			
+        mkdir $CARPETA_DESTINO
+        chmod 777 $CARPETA_DESTINO
+fi
+
+# Creo la carpeta fuente si no existe
+if [ ! -d "$CARPETA_FUENTE" ]; then			
+        mkdir $CARPETA_FUENTE
+        chmod 777 $CARPETA_FUENTE
+fi
 
 
-RETVAL=0
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+        # Return
+        #   0 if daemon has been started
+        #   1 if daemon was already running
+        #   2 if daemon could not be started
+
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+                || return 1
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+                $DAEMON_ARGS \
+                || return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+	[ "$?" = 2 ] && return 2
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	#
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+	#
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
+
 case "$1" in
-    start)
-	#si no se paso el nombre del dispositivo como 2do parametro
-	if [ -z "$2" ];	then
-		$SCRIPT &
-	else
-		$SCRIPT $2 &
-	fi
-	#sh $SCRIPTKEEPALIVE &
-	echo "se iniciaron los servicios del spooler correctamente";
-	RETVAL=$?
-    ;;
-    startonlyspooler)
-	$SCRIPT &
-	echo "se inicio solo el spooler correctamente";
-	RETVAL=$?
-    ;;
-    stop)
-      PROC_ID=`ps -fea | grep hasar_spooler | grep -v grep | awk '{print $2}'`
-      kill -9 $PROC_ID
-	  echo $PROC_ID
-      echo "Se cerro el hasar_spooler.sh - Proceso $PROC_ID"
+  start)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+echo "comenzando"
+        do_start
+echo "ya comennnnzooo"
+        case "$?" in
+                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+	;;
+  stop)
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  #reload|force-reload)
+	#
+	# If do_reload() is not implemented then leave this commented out
+	# and leave 'force-reload' as an alias for 'restart'.
+	#
+	#log_daemon_msg "Reloading $DESC" "$NAME"
+	#do_reload
+	#log_end_msg $?
+	#;;
+  restart|force-reload)
+	#
+	# If the "reload" option is implemented then remove the
+	# 'force-reload' alias
+	#
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+	  	# Failed to stop
+		log_end_msg 1
+		;;
+	esac
+	;;
+  *)
+	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
+	;;
+esac
 
-
-	  PROC_ID3=`ps -fea | grep spooler | grep -v grep | awk '{print $2}'`
-      kill -9 $PROC_ID3
-	  echo $PROC_ID3
-      echo "Se cerro el executable spooler - Proceso $PROC_ID3"
-      RETVAL=$?
-    ;;
-    restart)
-      #stop
-      #start
-	  cd /etc/init.d
-	  ./spooler_srv stop
-	  cd /etc/init.d
-	  ./spooler_srv start
-	  RETVAL=$?
-    ;;
-    *)
-      echo "Este es el servidor del spooler de Hasar: spoler_srv {start-startonlyspooler-stop-restart}"
-      exit 1
-  
-esac      
-exit $RETVAL
+:
